### ISSUE TITLE
Menu option 4 not working correctly

### ISSUE THREAD

**Issue by Xienshus** [candeladd/2270_Project_AC#8]
If you choose menu option 4 and enter a random number(I used the number 7 when I tested it), the program has a segmentation fault.

**Comment by austinholler** [comment]
It must be an older version because I just "re-cloned" the repo to my machine, tested it, and there was no seg fault.. 

If you enter option 4 first (i.e. without creating the user database) it asks that you create the database first (option 1). If you create the database (option 1), then choose option 4 and enter a 7 it says you entered an invalid genotype.

I'm messing around with it right now to fix any possibility of there being this kind of error. So let me know if there's still a problem in a few minutes.

Thanks so much!

**Comment by austinholler** [comment]
Commited last change so it should all work now with no input errors anymore!
